#pragma once

#include "utility/concepts.h"

#include <algorithm>
#include <bit>
#include <chrono>
#include <compare>
#include <concepts>
#include <coroutine>
#include <filesystem>
#include <format>
#include <fstream>
#include <functional>
#include <iostream>
#include <iterator>
#include <limits>
#include <memory>
#include <numbers>
#include <numeric>
#include <optional>
#include <random>
#include <ranges>
#include <ratio>
#include <regex>
#include <sstream>
#include <tuple>
#include <type_traits>
#include <utility>

#include <atomic>
#include <barrier>
#include <condition_variable>
#include <execution>
#include <future>
#include <latch>
#include <mutex>
#include <semaphore>
#include <thread>

#include <array>
#include <map>
#include <queue>
#include <set>
#include <span>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <vector>
